import turtle
def draw_square():
    window = turtle.Screen()
    window.bgcolor("black")
    brad = turtle.Turtle()
    brad.forward(100)
    brad.right(45)
    brad.forward(100)
    brad.right(45)
    brad.forward(100)
    brad.right(45)
    brad.forward(100)
    brad.right(45)
    window.exitonclick()
draw_square()
